-- MySQL Script generated by MySQL Workbench
-- mié 01 may 2019 19:50:24 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema builder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `closure_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NOT NULL,
  `child_id` BIGINT NOT NULL,
  `depth` BIGINT NOT NULL DEFAULT 0,
  `group_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC),
  INDEX `child_id` (`child_id` ASC),
  INDEX `group_id` (`group_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(150) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `closure_sort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `closure_sort` (
  `group_id` BIGINT NOT NULL,
  `node_id` BIGINT NOT NULL,
  `sort` BIGINT NOT NULL,
  UNIQUE INDEX `unique` (`group_id` ASC, `node_id` ASC),
  INDEX `sort` (`sort` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `closure_group`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure_group` (`id`, `name`) VALUES (1, 'priv');

COMMIT;


-- -----------------------------------------------------
-- Data for table `closure`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure` (`id`, `parent_id`, `child_id`, `depth`, `group_id`) VALUES (1, 1, 1, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `closure_node`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `closure_node` (`id`, `name`, `description`) VALUES (1, 'def', NULL);
INSERT INTO `closure_node` (`id`, `name`, `description`) VALUES (2, 'Global permissions', NULL);

COMMIT;

